default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :deploy_to_testflight do
    # If using match for code signing:
    # match(type: "appstore")
    build_app(
      scheme: "app",
      export_method: "app-store"
    )
    upload_to_testflight
  end
end