name: Deploy to Firebase + TestFlight

on:
  push:
    branches: [main]

defaults:
  run:
    working-directory: ./app

jobs:
  deploy:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 23.10.0
      - name: Set up npm
        run: |
          npm config set legacy-peer-deps false
          npm ci

      - name: Setup Cocoapods
        uses: maxim-lobanov/setup-cocoapods@v1.4.0
        with:
          podfile-path: ./app/ios/Podfile.lock

      # Android build
      # - name: Build Android SDK
      #   run: cd android && ./gradlew assembleRelease

      # - name: Upload to Firebase
      #   uses: wzieba/Firebase-Distribution-Github-Action@v1
      #   with:
      #     appId: ${{ secrets.FIREBASE_APP_ID }}
      #     token: ${{ secrets.FIREBASE_TOKEN }}
      #     groups: "dev-testers"
      #     file: app/android/app/build/outputs/apk/release/app-release.apk

      # - name: Install provisioning profile
      #   run: |
      #     mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
      #     echo "${{ secrets.IOS_PROVISIONING_PROFILE }}" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/verifyed-prov-prof.mobileprovision

      - name: Install Fastlane
        run: sudo gem install fastlane -NV

      # # iOS build
      - name: Install iOS Pods
        working-directory: ./app/ios
        run: pod install

      # - name: Setup Cocoapods
      #   uses: maxim-lobanov/setup-cocoapods@v1.4.0
      #   with:
      #     cocoapods-version: 1.9.0

      # - name: Archive iOS App
      #   working-directory: ./app/ios
      #   run: |
      #     xcodebuild -workspace app.xcworkspace \
      #       -scheme app \
      #       -sdk iphoneos \
      #       -configuration Release \
      #       -archivePath "$PWD/ios/build/app.xcarchive" \
      #       PROVISIONING_PROFILE_SPECIFIER=${{ secrets.PROVISIONING_PROFILE_SPECIFIER }} \
      #       DEVELOPMENT_TEAM=${{ secrets.APPLE_TEAM_ID }} \
      #       archive

      # - name: Upload to TestFlight
      #   uses: apple-actions/upload-testflight-build@v1
      #   with:
      #     app-path: ./app/ios/build/app.xcarchive
      #     issuer-id: ${{ secrets.APPLE_ISSUER_ID }}
      #     api-key-id: ${{ secrets.APPLE_KEY_ID }}
      #     api-private-key: ${{ secrets.APPLE_PRIVATE_KEY }}

      - name: Run Fastlane for TestFlight
        working-directory: ./app/ios
        env:
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APPLE_ISSUER_ID: ${{ secrets.APPLE_ISSUER_ID }}
          APPLE_KEY_ID: ${{ secrets.APPLE_KEY_ID }}
          APPLE_PRIVATE_KEY: ${{ secrets.APPLE_PRIVATE_KEY }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          GIT_URL: ${{ secrets.GIT_URL }}
        run: fastlane deploy_to_testflight
