name: Deploy to Firebase + TestFlight

on:
  push:
    branches: [main]

defaults:
  run:
    working-directory: ./app

jobs:
  deploy:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 23.10.0
      - name: Set up npm
        run: |
          npm config set legacy-peer-deps false
          npm ci

      - name: Setup Cocoapods
        uses: maxim-lobanov/setup-cocoapods@v1.4.0
        with:
          version: 1.9.0

      # Android build
      # - name: Build Android SDK
      #   run: cd android && ./gradlew assembleRelease

      # - name: Upload to Firebase
      #   uses: wzieba/Firebase-Distribution-Github-Action@v1
      #   with:
      #     appId: ${{ secrets.FIREBASE_APP_ID }}
      #     token: ${{ secrets.FIREBASE_TOKEN }}
      #     groups: "dev-testers"
      #     file: app/android/app/build/outputs/apk/release/app-release.apk

      - name: Testing APPLE Team ID presence
        run: |
          echo "APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}"
          echo "APPLE_TEAM_ID: ${{ secrets.APPLE_ISSUER_ID }}"
          echo "APPLE_TEAM_ID: ${{ secrets }}"
          if [ -z "${{ secrets.APPLE_TEAM_ID }}" ]; then
            echo "APPLE_TEAM_ID is not set"
            exit 1
          else
            echo "APPLE_TEAM_ID is set"
          fi

      # # iOS build
      - name: Install iOS Pods
        working-directory: ./app/ios
        run: pod install

      # - name: Setup Cocoapods
      #   uses: maxim-lobanov/setup-cocoapods@v1.4.0
      #   with:
      #     cocoapods-version: 1.9.0

      - name: Archive iOS App
        working-directory: ./app/ios
        run: |
          xcodebuild -workspace ios/app.xcworkspace \
            -scheme app \
            -sdk iphoneos \
            -configuration Release \
            -archivePath "$PWD/ios/build/app.xcarchive" \
            -allowProvisioningUpdates \
            -allowProvisioningDeviceRegistration \
            CODE_SIGN_STYLE=Automatic \
            DEVELOPMENT_TEAM=${{ secrets.APPLE_TEAM_ID }} \
            archive

      - name: Upload to TestFlight
        uses: apple-actions/upload-testflight-build@v1
        with:
          app-path: ios/build/app.xcarchive
          issuer-id: ${{ secrets.APPLE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPLE_KEY_ID }}
          api-private-key: ${{ secrets.APPLE_PRIVATE_KEY }}
