name: Deploy to Firebase + TestFlight

on:
  push:
    branches: [main]

defaults:
  run:
    working-directory: ./app

jobs:
  deploy:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 23.10.0
      - name: Set up npm
        run: |
          ls
          npm config set legacy-peer-deps false
          npm cache clean --force

          npm install
          npm ci

      # Android build
      # - name: Build Android SDK
      #   run: cd android && ./gradlew assembleRelease

      # - name: Upload to Firebase
      #   uses: wzieba/Firebase-Distribution-Github-Action@v1
      #   with:
      #     appId: ${{ secrets.FIREBASE_APP_ID }}
      #     token: ${{ secrets.FIREBASE_TOKEN }}
      #     groups: "dev-testers"
      #     file: app/android/app/build/outputs/apk/release/app-release.apk

      # # iOS build
      - name: Navigating to iOS directory
        run: cd ios && ls
      - name: Archive iOS App
        run: |
          xcodebuild -workspace app.xcworkspace \
            -scheme app \
            -sdk iphoneos \
            -configuration Release \
            -archivePath "$PWD/build/app.xcarchive" \
            -allowProvisioningUpdates \
            -allowProvisioningDeviceRegistration \
            -CODE_SIGN_STYLE=Automatic \
            -DEVELOPMENT_TEAM=${{ secrets.APPLE_TEAM_ID }} \
            archive

      - name: Upload to TestFlight
        uses: apple-actions/upload-testflight-build@v1
        with:
          app-path: ios/build/app.xcarchive
          issuer-id: ${{ secrets.APPLE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPLE_KEY_ID }}
          api-private-key: ${{ secrets.APPLE_PRIVATE_KEY }}
